#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config

# copy config
[[ ! -f /config/cupsd.conf ]] && cp \
	/defaults/cupsd.conf /config/cupsd.conf
[[ ! -f /config/cups-files.conf ]] && cp \
	/defaults/cups-files.conf /config/cups-files.conf

useradd -p $(openssl passwd -1 ${CUPS_ADMIN_PW:-cupsadmin}) -G lpadmin ${CUPS_ADMIN:-cupsadmin}

# permissions
chown -R abc:abc \
	/config \
	/var/cache/cups \
	/var/spool/cups \
	/run/cups